
sudo: false

language: ruby

cache:
- bundler

rvm:
  - 2.3.1

script: |
    bundle exec jekyll build &&
    bundle exec htmlproofer _site --assume-extension --check-html --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
