
# general
title: Özgür Akgün's Personal Webpage
email: ozgurakgun@gmail.com
description: This is Özgür Akgün's Personal Webpage.
baseurl: ""
url: "http://ozgurakgun.github.io"
twitter_username: ozgurakgun
github_username:  ozgurakgun

# build settings
markdown: kramdown
kramdown:
  input: GFM
include: ['_pages']







# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
