
# general
title: Özgür Akgün's Personal Website
email: ozgurakgun@gmail.com
description: This is Özgür Akgün's Personal Website.
baseurl: ""
url: "http://ozgurakgun.github.io"
twitter_username: ozgurakgun
github_username: ozgurakgun

# build settings
layouts_dir: __internal/layouts
markdown: kramdown
kramdown:
  input: GFM

exclude:
- vendor                # travis creates this directory during "install"
- README.md

collections:
- custom
- activities
- tags

collections:
  custom:
    output: true
    permalink: /:path
  activities:
    output: true
    permalink: /activity/:path
  tags:
    output: true
    permalink: /tag/:path

defaults:
  - scope:
      type: custom
    values:
      layout: custom
  - scope:
      type: activities
    values:
      layout: activity
  - scope:
      type: tags
    values:
      layout: tag
