
# personal info
title: Özgür Akgün
email: ozgurakgun@gmail.com
description: Özgür Akgün's personal homepage.
baseurl: ""
url: "http://ozgurakgun.github.io"
twitter_username: ozgurakgun
github_username: ozgurakgun

# Build settings
markdown: kramdown
theme: minima
