name: Building for github pages
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: bundle exec jekyll build
      - run: bundle exec htmlproofer _site --assume-extension --check-html --disable-external
